### ISSUE TITLE
Re-Pagination fork on AMO ?

### ISSUE THREAD

**Issue by tl-pierre** [Mathnerd314/repagination#1]
Hello,
You seem to have adapted Re-Pagination for Firefox 57+ (webextension), do you plan to make it available on addons.mozilla.org ? I think it would give more visibility to your fork !
Thank you

**Comment by Mathnerd314** [comment]
I uploaded a version, looks like it's been accepted. 
https://addons.mozilla.org/en-US/firefox/addon/re-pagination-webext-fork/

**Comment by tl-pierre** [comment]
Awesome ! Thank you very much for your work  :)
