### ISSUE TITLE
"% Pages" instead of "5 Pages"

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [Mathnerd314/repagination#11]
Hi

I have Win 10, FF 76, repagination from October 2019, all in German.

Problem:
Since long time, the Repagination menu does not show " 2 pages / 5 Pages / 10 Pages" (and seconds..), it shows "% pages / % pages / % pages / ..".
To be exact: "% Seiten / % Seiten / % Seiten / .." because it is in German.

What to do against it?

Thanks

**Comment by Mathnerd314** [comment]
Oh, I didn't change the German substitution thingies to match the new library. Thank you for pointing it out.

I've uploaded a new version to AMO which should be out momentarily, In the meantime you might look over https://github.com/Mathnerd314/repagination/blob/patch-2/_locales/de/messages.json for any other weird things.

**Comment by Pierre-de-la-Verre** [comment]
Already updated via FF.

Thanks. Good job!

**Comment by Pierre-de-la-Verre** [comment]
Thanks. Already updated via FF.
Good job!
