### ISSUE TITLE
Flatten menu structure

### ISSUE THREAD

**Issue by haarp** [Mathnerd314/repagination#2]
Thank you for forking this extension!

Now that FF57 requires a submenu anyway, I think we don't need two layers of menu structure. I also don't think we need so many different numbers. I propose this structure:

- Load all
- Load 2
- Load 10
- Load 25
- Load 50
- Load 100
- Stop

**Comment by Mathnerd314** [comment]
The current menu layout is no different from the old layout:
![image](https://user-images.githubusercontent.com/322214/33497785-52fcc3e6-d68c-11e7-9fac-20a592d7a0a6.png)
![image](https://user-images.githubusercontent.com/322214/33497832-77d4277c-d68c-11e7-88b4-d66a8095d329.png)

Also I'm not sure where the slideshow feature would go in your proposed layout.

**Comment by haarp** [comment]
Oh, I have never before seen that Slideshow menu. We could have it as a submenu before Stop.

Yes, it's the same menu depth indeed. I just find it to be needlessly complex, when one layer would do. I would very much prefer only having to navigate one submenu. But it's up to you to decide :)

**Comment by digital-carver** [comment]
Another possibility is to allow the user to rearrange the menu. For eg. I pretty much always use the Load 10 pages option, and have never used the Load all option through the years. It would be nice to be able to move the 'all' option into the subsubmenu and move the Load 10 pages into the current place of Load all. (This is assuming the WebExt api allows the menu arrangement to be programmatically reconfigured.)

**Comment by Mathnerd314** [comment]
I did Load 5 instead of Load 2, just because having them all multiples of 5 looks nicer. @digital-carver  for that level of customisation I'd just suggest forking the extension, menu code is in [createMenu](https://github.com/Mathnerd314/repagination/blob/0850b3e2841ec98e52b8771f934956f2801ed1cb/main.js#L27).

**Comment by haarp** [comment]
Looking great, thanks a lot!
