### ISSUE TITLE
Firefox 58.02

### ISSUE THREAD

**Issue by Orriky** [Mathnerd314/repagination#4]
It doesn't work on Firefox 58.02

**Comment by Mathnerd314** [comment]
Details? Site, browser error console (ctrl-shift-j), ...? It's been working fine for me on FF nightly (60.0a1).

**Comment by Orriky** [comment]
Yes, there are some errors. It's hard to understand the log but, maybe, "WebExtension context not found! ExtensionParent.jsm:830:13" is related to repagination




Error: Permission denied to access object  (sconosciuto)
XrayWrapper denied access to property "contains" (reason: value is callable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported.  content.js:355
Error: Permission denied to access object (sconosciuto)
XrayWrapper denied access to property "isAvailable" (reason: value is callable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported.  ExtensionUtils.jsm:514:50
Error: Promised response from onMessage listener at init@moz-extension://89abe6c7-927c-4ca5-8e1d-1b437119f5f4/dist/browser-core.js:17573:5 went out of scope undefined
Error: Permission denied to access object (sconosciuto)
Evento da tastiera non disponibile in alcuni layout di tastiera: tasto=“r” modificatori=“accel,alt” id=“key_toggleReaderMode”  browser.xul
Evento da tastiera non disponibile in alcuni layout di tastiera: tasto=“i” modificatori=“accel,alt,shift” id=“key_browserToolbox”  browser.xul
Error: Permission denied to access object (sconosciuto)
Error: Permission denied to access object (sconosciuto)
Error: WebExtension context not found! ExtensionParent.jsm:830:13
XrayWrapper denied access to property "contains" (reason: value is callable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported.  content.js:355
Sync encountered an error - see about:sync-log for the log file.  policies.js:773
Error: Permission denied to access object  (sconosciuto)
Warning: attempting to write 5560 bytes to preference browser.uiCustomization.state. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.

**Comment by Mathnerd314** [comment]
None of those look related to Repagination.

What exactly doesn't work? Does the menu show up? Do any errors appear in the browser console after you click Load X? Which site are you trying to use Repagination on?

Maybe try resetting Firefox: https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings

**Comment by Orriky** [comment]
I tried it in a fresh Firefox installation and it doesn't work.
Maybe I use it in a wrong way.
I opened [Google](www.google.com) and from the context menu I chose Re-Pagination>Limited>2 pages
Then I scrolled till the end of the page and nothing has happened. I expected the second page was automatically loaded

**Comment by Mathnerd314** [comment]
Oh, you have to use it on a link, like "Next" or an arrow.
When I try Google I get a blank page because their site loads some CSS which hides everything.  But it works fine on Bing, e.g. try it on the right arrow button on https://www.bing.com/search?q=test&pc=MOZI&first=9&FORM=PERE1

**Comment by Orriky** [comment]
Thanks
