### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by vertigo220** [Mathnerd314/repagination#5]
Tested in Waterfox 56.1.0x64 and a mostly fresh Firefox 59.0.3x64 with only a few addons and all but this one disabled, both with Google search, and it randomly either didn't do anything or, more often, it counted the # of pages in the tab/title then loaded a blank page.

**Comment by Mathnerd314** [comment]
Google was loading a stylesheet that blanked the page, fixed in most recent version.
