### ISSUE TITLE
Auto feature

### ISSUE THREAD

**Issue by vertigo220** [Mathnerd314/repagination#7]
Needs auto feature for specified sites, so they're automatically paginated (e.g. www.google.com).

**Comment by Mathnerd314** [comment]
Why can't you use one of the already existing addons, like [AutoPagerize](https://addons.mozilla.org/en-US/firefox/addon/autopagerize/) or [uAutoPagerize](https://addons.mozilla.org/en-US/firefox/addon/uautopagerize/)?

**Comment by Mathnerd314** [comment]
Closing as it seems those work OK for you and I myself have no interest in automatic pagination ('infinite scrolling'). A [UI study](https://www.smashingmagazine.com/2016/03/pagination-infinite-scrolling-load-more-buttons/) shows that it decreases page interaction, and then there are also the practical issues like access to the footer, jumpy scroll bar, page load overhead, and losing your place on page navigation. Re-pagination implements the UI pattern the article recommends (the 'Load more' button) and has none of the practical issues.
<img src="https://camo.githubusercontent.com/e0c2a03de026456d764f0d30700ac9aecfc61697/68747470733a2f2f696d67732e786b63642e636f6d2f636f6d6963732f696e66696e6974655f7363726f6c6c696e675f32782e706e67" alt="" data-canonical-src="https://imgs.xkcd.com/comics/infinite_scrolling_2x.png" width="249" height="348">
