### ISSUE TITLE
features suggestion

### ISSUE THREAD

**Issue by Mike-Reddick** [Mathnerd314/repagination#9]
Please add an context menu entry to use an custom value, and an feature to "re-paginate" dragging link, the user can choose an default value, ex 5 pages, and when drag, load 5, need option to choose drag direction to keep compatibility with other drag plugins. I like this plugin a lot but the context menu sometimes is hard to use, with drag can be very easy, I can use it much more. You can even implement two drag modes:

Mode 1: Load direct to an configurable value (ex 5 pages)

Mode 2: Show an popup with options (ex 5, 10, 20 etc)

Thanks so much!

**Comment by Mathnerd314** [comment]
It would be fairly easy to add another configuration option to configure the menu, it is just a list of the number of pages to load: https://github.com/Mathnerd314/repagination/blob/patch-2/main.js#L36

As far as dragging, I guess you are referring to gesture addons like Gesturefy? The easiest thing there for Mode 1 would be to set up Gesturefy to send a cross-extension message: https://github.com/Robbendebiene/Gesturefy/wiki/Send-message-to-other-addon. I could support that pretty easily.

It doesn't look like Firefox allows creating real popups from extensions, so showing a popup on a gesture is more complicated. For Mode 2 I think you would have to modify Gesturefy to support showing the list of options and picking one out, similar to the existing [popups](https://github.com/Robbendebiene/Gesturefy/blob/master/src/core/commands.js#L1303). But the receiving code in Re-Pagination would be unchanged.

What do you think?

**Comment by Mike-Reddick** [comment]
About the gestures, is not exactly like  Gesturefy which is gestures to navigation  , but more like "Glitter Drag" extension which is specialized in gestures dragging links, I like the idea of "a cross-extension message" the issue is which the Glitter Drag haven't the option to set an action with an "custom message", so, implementing this feature as "a cross-extension message" can require an feature of another extension. Ideal is "a cross-extension message" I agree with you, but in real word this make "Repagination" extension dependent, maybe better an independent "link gesture implementation"? Maybe "Glitter Drag" developer can implement an "custom message" if we ask it? I don't know. About the popup, really seem the webextension not allow an real popup :( I think the solution is an fake popup as used by "Swift Selection Search" extension. 

Just an note: In the past I used to navigation Firegestures, but with webextension "navigation gestures" extension is much limited, so today I use StrokePlus an external software to "navigation gestures" and to "link gestures" I use the webextension Glitter Drag.

Thanks your attention!

**Comment by Mike-Reddick** [comment]
As you can see I open an issue on Glitter Drag, but have others open issues without any reply,

**Comment by Mathnerd314** [comment]
There is also https://github.com/marklieberman/foxygestures, it is a direct descendant of Firegestures. And a few others: https://addons.mozilla.org/en-US/firefox/addon/fire-drag/ https://addons.mozilla.org/en-US/firefox/addon/simple_mouse_gestures/ https://addons.mozilla.org/en-US/firefox/addon/quickdrag-we/ https://addons.mozilla.org/en-US/firefox/addon/drag-to-go/ https://addons.mozilla.org/en-US/firefox/addon/hyper-drag/

I really don't want to write my own drag/gesture extension, surely one of those is alright :pensive:

**Comment by Mike-Reddick** [comment]
Yes I know, have other extensions to drag link, but have at least one with "a cross-extension message" action? The question is why implement "a cross-extension message" if have any extension which can use it, Foxygestures haven't any drag link feature, Foxygestures  is just for navigation, I don't know any "drag link" extension with "cross-extension message"

**Comment by Mike-Reddick** [comment]
@Mathnerd314 ?

**Comment by Mike-Reddick** [comment]
I found the solution to all this issues, the PageZipper extenssion, thanks so much developer to all the attention!

**Comment by Mathnerd314** [comment]
I see. Glad you found a solution! You could also try https://addons.mozilla.org/en-US/firefox/addon/weautopagerize/. It is similar to PageZipper but has been updated more recently.
